version: '3.1'
services: 
  app:
    container_name: 'app'
    build: '.'
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
    ports: 
      - '8080:8080'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:4.0'
    container_name: 'mongo'
    ports: 
      - '27017:27017'

